name: "build-release"

on:
  push:
    paths: 
      - '**.py'
      - '**.yml'
      - '**.json'
      - '**.png'
    branches:
      - "main"
jobs:

  build:
    name: Build exe and wheel
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: pip install -r src/requirements.txt pyinstaller
    - run: pyinstaller src/KUMA.spec
    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: KUMA
        path: dist/KUMA.exe
    
    - name: "Automatic Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest release"
          files: |
            ./dist/KUMA.exe